### ISSUE TITLE
File inspector

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#116]
Add a doctor function to detect file issues and offer repair options:
- [ ] mention annotations that do not start on token boundaries
- [ ] singletons
- [ ] entity groups with less than two members

This also fixes #115

**Comment by andreasvc** [comment]
Another useful thing to check:
- duplicate mentions (identical spans) within the same entitity
- duplicate spans across different entities

These create warnings in the coreference evaluation tool but they are hard to track down since it doesn't report where in the file they occur. IMHO duplicate spans shouldn't be allowed at all, but if they are, checking for them is useful.

**Comment by nilsreiter** [comment]
Duplicate mentions of an entity can actually be removed automatically via the context menu.

**Comment by andreasvc** [comment]
That's nice, but it doesn't solve the problem of discovering them right? The coreference evaluation tool told me they were there, but it reports them with its own internal IDs, so after that I still had to figure out which entity had the duplicate mention. So instead of a per-entity duplicate removal option, you could have an option to check and remove duplicate mentions globally.

**Comment by nilsreiter** [comment]
You can select multiple or all entities, and then remove duplicates on all of them. Just make sure you select only entities.
