### ISSUE TITLE
Export in BIO Format

### ISSUE THREAD

**Issue by aribornstein** [nilsreiter/CorefAnnotator#165]

**Comment by nilsreiter** [comment]
This trickier than it seems, since the tool doesn’t require that we have token spans. There is no basis to directly export to BIO. Integrating a tokenizer also is language-dependent. Have to think about that. 

In the meantime: export to UIMA/DKpro, and run one of its tokenizers and the BIO export from there.

**Comment by nilsreiter** [comment]
also, forgot to mention, there is already a CoNLL export, which is essentially BIO.
