### ISSUE TITLE
Coref-Annotator freezes when deleting an annotation

### ISSUE THREAD

**Issue by michaelgoeggelmann** [nilsreiter/CorefAnnotator#381]
If you right-click on an annotation, there are two "Delete" fields. The "inner" field (highlighted in blue in the screenshot) inevitably leads to a "freeze" of the entire program. Only saving the file is still possible. If this is affirmed, the file is corrupt afterwards and cannot be opened again by the Coref annotator.

![grafik](https://user-images.githubusercontent.com/81326331/133744285-9f7806ae-d068-4a2f-a551-df8e9f24be04.png)

**Comment by bkis** [comment]
I want to briefly capture some observations I made that will likely be helpful for resolving this issue (I'm "on it").

![image](https://user-images.githubusercontent.com/9215743/143219123-ca863eca-b4d6-4a09-bf7d-251cc3db64d5.png)

Some things to structure the conceptual context (possible/needed fixes/improvements marked with 🐛):

- The entry `15: magna` in the top popup menu looks like it refers to the entity name, not the specific mention. They are the same in this example, but if we added e.g. _"amet"_ as a mention of the entity _"magna"_ and then right-clicked on it, the entry would still say `n: magna` (with a different number). But, in fact, the entry refers to the specific mention - so maybe it would be more intuitive to label this entry something like `n: amet (magna)` in this case (that is: `index: mention (entity)`). 🐛
- The `Delete` item in the second-level popup menu (labeled **1** in the screenshot) is for deleting this specific mention (!) completely. A single mention can consist of multiple (possibly scattered) words (or, to stick to the term used in the code, _surfaces_). The mention `Lorem | dolor` of the entity `Lorem` in the screenshot is an example for this. A click on `Delete` (**1**) is supposed to remove both _surfaces_ of the mention `Lorem | dolor`, so `Lorem` **and** `dolor`. This works as expected.
- The menu entry `magna` below the `Delete` (**1**) is superfluous for mentions that only have one _surface_ (like in the example) because its purpose is to be able to delete a specific _surface_ of a mention. If there is only one, the `Delete` (**1**) would suffice. 🐛
  - This is a very easy fix (if we want it at all): We'd just have to change `if (m.getSurface().size() > 0)` in the class _DocumentWindow_ to `if (m.getSurface().size() > 1)`.
- **But**, unfortunately, that doesn't solve the problem. It doesn't matter whether a mention consists of multiple _surfaces_ or not: A click on `Delete` (**2**) in the third-level popup menu (that's supposed to delete a specific _surface_), always results in a `NullPointerException` and the surface being (visually) removed from the tree view but not from the document view. 🐛

I consider these points useful finding a solution. Take them as a public personal note :)
I'll look further into this and update this issue with my findings...
